name: youtube-dl-pro
base: core20
version: '2.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Download videos or playlist or music audio from youtube.com in full HD formats
description: DL-YOUTUBE PRO is a powerful GUI application for linux for downloading youtube videos, playlist and music audio in full UHD+ resolutions and supports MP4, WEBM and MP3 formats.
grade: stable # must be 'stable' to release into candidate/stable channels  / before dev use devel
confinement: strict # use 'strict' once you have the right plugs and slots / before dev use devmode

icon: snap/gui/icon.png

architectures:
  - build-on: [amd64]

environment:
  SNAP_DESKTOP_RUNTIME: $SNAP/glances-pro
  
apps:
  youtube-dl-pro:
    command: bin/desktop-launch youtube-dl-pro
    desktop: youtube-dl-pro.desktop
    environment:
      DISABLE_WAYLAND: 1
      
    plugs: 
       - home
       - gsettings
       - network
       - network-bind
       - network-status
       - desktop
       - desktop-legacy
       - x11
       - unity7
       - wayland
       - opengl
       - audio-playback
       - hardware-observe

plugs:
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  glances-pro:
    interface: content
    target: $SNAP/glances-pro
    default-provider: glances-pro


parts:
  snap-launcher:
    plugin: dump
    source: snap_launcher/    
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=.*|Icon=${SNAP}/meta/gui/icon.png|g' ${SNAPCRAFT_PART_SRC}/youtube-dl-pro.desktop
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/
      cp -rf ${SNAPCRAFT_PART_SRC}/youtube-dl-pro.desktop ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/youtube-dl-pro.desktop
  

  youtube-dl-pro:
    plugin: python
    source: .
    python-packages:
      - requests
      - cryptography
      - psutil
      - python-slugify
      - yt-dlp
    build-attributes: [ keep-execstack ]