name: youtube-dl-pro
base: core18 # the base snap is the execution environment for this snap
version: '0.4' # just for humans, typically '1.2+git' or '1.3.2'
summary: Download videos or playlist or music audio from youtube.com in full HD formats
description: |
  Youtube-dl-Pro is a powerful GUI application for linux for downloading youtube videos, playlist and music audio in full UHD+ resolutions and supports MP4, WEBM and MP3 formats.
grade: stable # must be 'stable' to release into candidate/stable channels  / before dev use devel
confinement: strict # use 'strict' once you have the right plugs and slots / before dev use devmode

icon: snap/gui/icon.png

architectures:
  - build-on: [amd64]

apps:
  youtube-dl-pro:
    command: bin/desktop-launch python3 $SNAP/youtube-dl-pro.py
    plugs: 
       - home
       - gsettings
       - network
       - network-bind
       - network-status
       - desktop
       - desktop-legacy
       - x11
       - unity7
       - wayland
       - opengl
       - audio-playback
       - hardware-observe

    desktop: youtube-dl-pro.desktop

plugs:
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  pyqt5-runtime:
    interface: content
    target: $SNAP/pyqt5-runtime
    default-provider: pyqt5-runtime


parts:
  desktop-gui:
    plugin: dump
    source: src/
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=.*|Icon=${SNAP}/meta/gui/icon.png|g' ${SNAPCRAFT_PART_SRC}/youtube-dl-pro.desktop
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/
      cp -rf ${SNAPCRAFT_PART_SRC}/youtube-dl-pro.desktop ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/youtube-dl-pro.desktop


  snap-launcher:
    plugin: dump
    source: snap_launcher/

  youtube-dl-pro:
      plugin: python
      python-version: python3
      source: .
      python-packages: 
          - requests
          - cryptography
          - pytube
          - psutil
          - ffmpeg-python
          - python-slugify
          - youtube_dl
      build-attributes: [ keep-execstack ]
